# This file defines the menus on the website. See the documentation for
# details: https://docs.bolt.cm/configuration/menus

main:
    - label: Spark Developmnent
      title: Learn more about our spark development
      path: homepage
      class: first
    - label: Units
      path: units/
    - label: News
      path: news/
    - label: Contact
      path: contact/
    - label: The Bolt site
      link: http://bolt.cm
      class: last
